keyrock:
  fullnameOverride: keyrock
  statefulset:
    image:
      repository: quay.io/wi_stefan/keyrock
      tag: sn-fix
      pullPolicy: IfNotPresent

  db:
    user: root
    host: mysql-iam

  admin:
    user: admin
    email: admin@fiware.org

  existingSecret: keyrock-secret

  host: https://ar.doma-iam.fiware.dev
  
  route:
    enabled: true
    routes:
      - host: ar.dome-iam.fiware.dev
        tls:
          termination: edge
          insecureEdgeTerminationPolicy: Redirect
        # should a certificate for the address automatically be generated
        certificate:
          issuer: 
            kind: ClusterIssuer
            name: letsencrypt-aws-prod

  ## Theme configuration for Keyrock
  theme:
    ## -- Enable theme
    enabled: false

  ## Configuration of Authorisation Registry (AR)
  authorisationRegistry:
    # -- Enable usage of authorisation registry
    enabled: true
    # -- Identifier (EORI) of AR
    identifier: "did:web:dome-iam.fiware.dev:did"
    # -- URL of AR
    url: "internal"

  ## Configuration of iSHARE Satellite
  satellite:
    # -- Enable usage of satellite
    enabled: true
    # -- Identifier (EORI) of satellite
    identifier: "EU.EORI.FIWARESATELLITE"
    # -- URL of satellite
    url: "https://tir.dome-iam.fiware.dev"
    # -- Token endpoint of satellite
    tokenEndpoint: "https://tir.dome-iam.fiware.dev/token"
    # -- Parties endpoint of satellite
    partiesEndpoint: "https://tir.dome-iam.fiware.dev/parties"

  ## -- Configuration of local key and certificate for validation and generation of tokens
  token:
    enabled: false

  
  additionalEnvVars:
    - name: IDM_TITLE
      value: "DOME IAM AR"
    - name: IDM_DEBUG
      value: "true"
    - name: DEBUG
      value: "*"
    - name: IDM_DB_NAME
      value: bp_one_idm
    - name: IDM_DB_SEED
      value: "true"
    - name: IDM_SERVER_MAX_HEADER_SIZE
      value: "32768"
    - name: IDM_EMAIL_HOST
      value: "mailgun-fiware-io.infra.svc.cluster.local"
    - name: IDM_EMAIL_PORT
      value: "25"
    - name: IDM_EMAIL_ADDRESS
      value: "bp-one@fiware.io"
    - name: IDM_PR_CLIENT_ID
      value: "did:web:dome-iam.fiware.dev:did"
    - name: IDM_PR_CLIENT_KEY
      valueFrom:
        secretKeyRef:
          name: waltid-vcwaltid-tls-sec
          key: tls.key
    - name: IDM_PR_CLIENT_CRT
      valueFrom:
        secretKeyRef:
          name: waltid-vcwaltid-tls-sec
          key: tls.crt
## Init scripts for Keyrock
initScript:
  ## Creation of role mapping policies during deployment
  rolePolicy:
    policyEnabled: true
    dbName: bp_one_idm
    issuer: "did:web:dome-iam.fiware.dev:did"
    notBefore: "1616583866"
    notOnOrAfter: "1735817171"
    issuerDid: "did:web:dome-iam.fiware.dev:did"