apiVersion: v2
name: vcverifier
description: vcverifier chart

type: application
version: 0.0.1
appVersion: "1.0.23"

dependencies:
  - name: vcverifier
    version: 1.0.23
    repository: https://i4Trust.github.io/helm-charts
