vcverifier:

  deployment:

    # Image
    image:
      repository: quay.io/fiware/vcverifier
      tag: 2.8.0
      pullPolicy: Always

    # Logging
    logging: 
      level: DEBUG
      pathsToSkip: 
        - "/health"

    # Walt-id config
    ssikit:
      auditorUrl: http://waltid-vcwaltid:7003

    # Verifier config
    verifier:
      tirAddress: https://tir.dome-iam.fiware.dev/v4/issuers
      did: did:web:dome-iam.fiware.dev:did

    # Config service
    configRepo:
      configEndpoint: http://ccs-credentials-config-service:8080/

  route:
    enabled: true
    host: verifier.dome-iam.fiware.dev
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    certificate:
      issuer:
        kind: ClusterIssuer
        name: letsencrypt-aws-prod
  
