## configuration of postgres to be used for the keycloak - see https://github.com/bitnami/charts/tree/main/bitnami/postgresql for details
postgresql:
  # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
  fullnameOverride: postgresql-iam
  ## auth configuration for the database
  auth:
    # -- username to be used
    username: keycloak
    # -- should the default postgres user be enabled
    enablePostgresUser: true
    # -- password to be used
    password: postgres
    # credentials for postgres admin user
    postgresPassword: postgres
  ## creates role for ServiceAccount
  rbac:
    # -- should role be created
    create: true
    ## rules applied to the role
    rules:
      - apiGroups:
          - security.openshift.io
        resourceNames:
          - anyuid
        resources:
          - securitycontextconstraints
        verbs:
          - use
  ## configuration of the postgres primary replica
  primary:
    ## provide db initialization
    initdb:
      ## provide scripts for initialization
      scripts:
        # -- create the database as expected by the keycloak
        create.sh: |
          psql postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE keycloak_iam;"

## configuration of mysql to be used for TIL, CCS and Keyrock - see https://github.com/bitnami/charts/tree/main/bitnami/mysql for details
mysql:
  fullnameOverride: mysql-iam
  auth:
    rootPassword: password
    password: password
    replicationPassword: password
  rbac:
    create: true
    rules:
      - apiGroups:
          - security.openshift.io
        resourceNames:
          - anyuid
        resources:
          - securitycontextconstraints
        verbs:
          - use
  initdbScripts:
    create.sql: |
      CREATE DATABASE til;
      CREATE DATABASE ccs;

## configuration of waltid to be used for keycloak and verifier - see https://github.com/dome-marketplace/iam-components/tree/main/charts/walt-id for details
vcwaltid:
  # -- did
  did: did:web:dome-iam.fiware.dev:did
  # -- jwkKid
  jwkKid: 6f4c1255f4a54090bc8ff7365b13a9b7
  ## route configuration
  route:
    enabled: true
    # -- host under which waltid will be available
    host: dome-iam.fiware.dev
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    certificate:
      issuer:
        kind: ClusterIssuer
        name: letsencrypt-aws-prod

  fullnameOverride: waltid-iam
  ## deployment specific configuration
  deployment:
    ## deployment image
    image:
      # -- deployment image repository
      repository: waltid/ssikit
      # -- deployment image tag
      tag: 1.2311262046.fix-didwebpath
      # -- deployment image pull policy
      pullPolicy: Always
  api:
    core:
      enabled: true
    auditor:
      enabled: true
    signatory:
      enabled: true
    custodian:
      enabled: true
    essif:
      enabled: true

  persistence:
    enabled: true
    pvc:
      size: 1Gi
  ## credential templates
  templates:
    SomeService.json: |
      {
        "@context": ["https://www.w3.org/2018/credentials/v1"],
        "credentialSchema": {
          "id": "https://raw.githubusercontent.com/FIWARE-Ops/i4trust-provider/main/docs/schema.json",
          "type": "FullJsonSchemaValidator2021"
        },
        "credentialSubject": {
          "id": "did:ebsi:2AEMAqXWKYMu1JHPAgGcga4dxu7ThgfgN95VyJBJGZbSJUtp",
          "roles": [{
            "names": ["CREATE_ISSUER"],
            "target": "did:elsi:someservice"
          }]
        },
        "id": "urn:uuid:3add94f4-28ec-42a1-8704-4e4aa51006b4",
        "issued": "2021-08-31T00:00:00Z",
        "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
        "validFrom": "2021-08-31T00:00:00Z",
        "issuanceDate": "2021-08-31T00:00:00Z",
        "type": ["VerifiableCredential", "SomeService"]
      }
    M2MTirCredential.json: |
      {
        "@context": [
          "https://www.w3.org/2018/credentials/v1"
        ],
        "credentialSubject": {
          "id": "did:ebsi:2AEMAqXWKYMu1JHPAgGcga4dxu7ThgfgN95VyJBJGZbSJUtp",
          "roles": [
            {
              "names": [
                "CREATE_ISSUER"
              ],
              "target": "did:web:somware.space"
            }
          ]
        },
        "id": "urn:uuid:3add94f4-28ec-42a1-8704-4e4aa51006b4",
        "issued": "2021-08-31T00:00:00Z",
        "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
        "validFrom": "2021-08-31T00:00:00Z",
        "issuanceDate": "2021-08-31T00:00:00Z",
        "type": [
            "VerifiableCredential"
        ]
      }

keycloak:
  fullnameOverride: keycloak-iam

  route:
    enabled: true
    host: kc.dome-iam.fiware.dev
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    certificate:
      issuer:
        kind: ClusterIssuer
        name: letsencrypt-aws-prod

  realm:
    clients:
      - did: did:web:some-service.dome-iam.fiware.dev:did
        description: Client to connect to some service
        roles:
          - name: CREATE_ISSUER
            description: Is allowed to create issuers
          - name: UPDATE_ISSUER
            description: Is allowed to update issuers
          - name: DELETE_ISSUER
            description: Is allowed to delete issuers
        vc:
          name: SomeService
          types:
            - ldp_vc
            - jwt_vc_json
          claims:
            - email
            - firstName
            - familyName
            - roles
      - did: did:web:onboarding.dome-iam.fiware.dev:did
        description: Client to issue credentials for M2M communication with the onboarding-tir
        roles:
          - name: TIR_READER
            description: Is allowed to read from the tir
        vc:
          name: M2MTirCredential
          types:
            - ldp_vc
            - jwt_vc_json
          claims:
            - roles
    users:
      - username: domeIam
        password: domeIam
        clientRoles:
          - clientDid: did:web:some-service.dome-iam.fiware.dev:did
            roles:
              - CREATE_ISSUER
              - UPDATE_ISSUER
          - clientDid: did:web:onboarding.dome-iam.fiware.dev:did
            roles:
              - TIR_READER

  image:
    tag: 21.1.2-debian-11-r1
  service:
    type: ClusterIP
  logging:
    level: INFO
  replicaCount: 1
  auth:
    adminUser: fiwareAdmin
    adminPassword: fiwareAdmin
  serviceAccount:
    create: true
  rbac:
    create: true
    rules:
      - apiGroups:
          - security.openshift.io
        resourceNames:
          - anyuid
        resources:
          - securitycontextconstraints
        verbs:
          - use


  keycloakConfigCli:
    enabled: true
    # current image does not contain 20.0.3., thus we need this fix
    command:
      - java
      - -jar
      - /opt/bitnami/keycloak-config-cli/keycloak-config-cli-20.0.1.jar

    extraEnvVars:
      - name: IMPORT_FILES_LOCATIONS
        value: "/config/*"
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false
    existingConfigmap: keycloak-iam-realm

  extraEnvVars:
    - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_LOG_LEVEL
      value: INFO
    - name: VCISSUER_ISSUER_DID
      value: "did:web:dome-iam.fiware.dev:did"
    - name: VCISSUER_WALTID_ADDRESS
      value: "http://waltid-iam"


  extraVolumeMounts:
    - name: profiles
      mountPath: /opt/bitnami/keycloak/conf/profile.properties
      subPath: profile.properties
    - name: providers
      mountPath: /opt/bitnami/keycloak/providers/
    - name: issuer-key
      mountPath: /opt/keys
    - name: data
      mountPath: /data


  extraVolumes:
    - name: data
      emptyDir: {}
    - name: profiles
      configMap:
        name: keycloak-iam-profile
    - name: providers
      emptyDir: {}
    - name: issuer-key
      configMap:
        name: keycloak-iam-key
    - name: did-config
      configMap:
        name: keycloak-iam-did-config
    - name: did-secret
      secret:
        secretName: waltid-iam-tls-sec


  initContainers:
    - name: add-vc-issuer
      image: quay.io/fiware/keycloak-vc-issuer:1.0.2
      imagePullPolicy: Always
      volumeMounts:
        - name: providers
          mountPath: /target
    - name: load-did
      image: quay.io/opencloudio/curl:4.2.0-build.8
      imagePullPolicy: Always
      command:
        - /bin/sh
        - /opt/did/script/import.sh
      env:
        - name: WALTID_CORE_ADDRESS
          value: "waltid-iam:7000"
      volumeMounts:
        - name: did-config
          mountPath: /opt/did/script
        - name: did-secret
          mountPath: /opt/did/secret

  postgresql:
    enabled: false

  externalDatabase:
    host: postgresql-iam
    user: postgres
    database: keycloak_iam
    password: postgres
