## configuration of postgres to be used for the keycloak - see https://github.com/bitnami/charts/tree/main/bitnami/postgresql for details
postgresql:
  # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
  fullnameOverride: postgresql-iam
  ## auth configuration for the database
  auth:
    # -- username to be used
    username: keycloak
    # -- should the default postgres user be enabled
    enablePostgresUser: true
    # -- password to be used
    password: postgres
    # credentials for postgres admin user
    postgresPassword: postgres
  ## creates role for ServiceAccount
  rbac:
    # -- should role be created
    create: true
    ## rules applied to the role
    rules:
      - apiGroups:
          - security.openshift.io
        resourceNames:
          - anyuid
        resources:
          - securitycontextconstraints
        verbs:
          - use
  ## configuration of the postgres primary replica
  primary:
    ## provide db initialization
    initdb:
      ## provide scripts for initialization
      scripts:
        # -- create the database as expected by the keycloak
        create.sh: |
          psql postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE keycloak_iam;"

## configuration of mysql to be used for TIL, CCS and Keyrock - see https://github.com/bitnami/charts/tree/main/bitnami/mysql for details
mysql:
  fullnameOverride: mysql-iam
  auth:
    rootPassword: password
    password: password
    replicationPassword: password
  rbac:
    create: true
    rules:
      - apiGroups:
          - security.openshift.io
        resourceNames:
          - anyuid
        resources:
          - securitycontextconstraints
        verbs:
          - use
  initdbScripts:
    create.sql: |
      CREATE DATABASE til;
      CREATE DATABASE ccs;

## configuration of waltid to be used for keycloak and verifier - see https://github.com/dome-marketplace/iam-components/tree/main/charts/walt-id for details
vcwaltid:
  # -- fullname
  fullnameOverride: vcwaltid
  # -- did
  did: did:web:dome-iam.fiware.dev:did
  # -- jwkKid
  jwkKid: 6f4c1255f4a54090bc8ff7365b13a9b7
  ## route configuration
  route:
    enabled: true
    # -- host under which waltid will be available
    host: dome-iam.fiware.dev
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    certificate:
      issuer:
        kind: ClusterIssuer
        name: letsencrypt-aws-prod
  ## deployment specific configuration
  deployment:
    ## deployment image
    image:
      # -- deployment image repository
      repository: waltid/ssikit
      # -- deployment image tag
      tag: 1.2311262046.fix-didwebpath
      # -- deployment image pull policy
      pullPolicy: Always
  api:
    core:
      enabled: true
    auditor:
      enabled: true
    signatory:
      enabled: true
    custodian:
      enabled: true
    essif:
      enabled: true

  persistence:
    enabled: true
    pvc:
      size: 1Gi
  ## credential templates
  templates:
    SomeService.json: |
      {
        "@context": ["https://www.w3.org/2018/credentials/v1"],
        "credentialSchema": {
          "id": "https://raw.githubusercontent.com/FIWARE-Ops/i4trust-provider/main/docs/schema.json",
          "type": "FullJsonSchemaValidator2021"
        },
        "credentialSubject": {
          "id": "did:ebsi:2AEMAqXWKYMu1JHPAgGcga4dxu7ThgfgN95VyJBJGZbSJUtp",
          "roles": [{
            "names": ["CREATE_ISSUER"],
            "target": "did:elsi:someservice"
          }]
        },
        "id": "urn:uuid:3add94f4-28ec-42a1-8704-4e4aa51006b4",
        "issued": "2021-08-31T00:00:00Z",
        "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
        "validFrom": "2021-08-31T00:00:00Z",
        "issuanceDate": "2021-08-31T00:00:00Z",
        "type": ["VerifiableCredential", "SomeService"]
      }
    M2MTirCredential.json: |
      {
        "@context": [
          "https://www.w3.org/2018/credentials/v1"
        ],
        "credentialSubject": {
          "id": "did:ebsi:2AEMAqXWKYMu1JHPAgGcga4dxu7ThgfgN95VyJBJGZbSJUtp",
          "roles": [
            {
              "names": [
                "CREATE_ISSUER"
              ],
              "target": "did:web:somware.space"
            }
          ]
        },
        "id": "urn:uuid:3add94f4-28ec-42a1-8704-4e4aa51006b4",
        "issued": "2021-08-31T00:00:00Z",
        "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
        "validFrom": "2021-08-31T00:00:00Z",
        "issuanceDate": "2021-08-31T00:00:00Z",
        "type": [
            "VerifiableCredential"
        ]
      }