apiVersion: v2
name: iam-components
description: Umbrella Chart for the DOME Marketplace iam-components
type: application
version: 0.0.1-PRE-4
appVersion: 0.0.1
dependencies:
  - name: postgresql
    version: 12.1.13
    repository: https://charts.bitnami.com/bitnami
  - name: mysql
    version: 9.4.4
    repository: https://charts.bitnami.com/bitnami
  - name: vcwaltid
    version: 0.0.18
    repository: https://i4trust.github.io/helm-charts
  - name: keycloak
    version: 13.0.3
    repository: https://charts.bitnami.com/bitnami
  - name: credentials-config-service
    version: 0.0.4
    repository: https://fiware.github.io/helm-charts
  - name: trusted-issuers-list
    version: 0.5.3
    repository: https://fiware.github.io/helm-charts
  - name: trusted-issuers-registry
    version: 0.0.11
    repository: https://fiware.github.io/helm-charts
  - name: vcverifier
    version: 1.0.23
    repository: https://i4trust.github.io/helm-charts
  - name: keyrock
    version: 0.7.5
    repository: https://fiware.github.io/helm-charts
  - name: dsba-pdp
    version: 0.0.17
    repository: https://fiware.github.io/helm-charts
  - name: kong
    version: 2.10.0
    repository: https://charts.konghq.com
  - name: orion
    version: 1.2.6
    repository: https://fiware.github.io/helm-charts
