{{- if .Values.kong.dblessConfig.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kong.dblessConfig.configMap }}
data:
  kong.yml: |
    _format_version: "2.1"
    _transform: true

    services:

      - host: "orion-ld"
        name: "orion-ld"
        port: 1026
        protocol: http
    
        routes:
          - name: orion-ld
            paths:
              - /orion-ld
            strip_path: true
    
        plugins:
          - name: pep-plugin
            config:
              pathprefix: "/orion-ld"
              authorizationendpointtype: ExtAuthz
              authorizationendpointaddress: http://pdp-iam:8080/authz
                
          - name: request-transformer
            config:
              remove:
                headers:
                  - Authorization
                  - authorization

  {{- end }}