{{- if .Values.kong.dblessConfig.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kong.dblessConfig.configMap }}
data:
  kong.yml: |
    _format_version: "2.1"
    _transform: true

    consumers:
    - username: token-consumer
      keyauth_credentials:
      - tags: 
        - token-key
        - tir-key

    services:

      - host: "protected-service"
        name: "vc"
        port: 8080
        protocol: http
    
        routes:
          - name: vc
            paths:
              - /vc
            strip_path: true
    
        plugins:
          - name: pep-plugin
            config:
              pathprefix: "/vc"
              authorizationendpointtype: ExtAuthz
              authorizationendpointaddress: http://pdp-iam:8080/authz
                
          - name: request-transformer
            config:
              remove:
                headers:
                  - Authorization
                  - authorization

  {{- end }}